name: Test Package

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ^20.9.0
      - run: yarn
      - run: yarn test
      - uses: actions/upload-artifact@v4
        with:
          name: coverage.json
          path: coverage/coverage-final.json
