---
name: Run test with jest
description: Run npm run test

on:  # yamllint disable-line rule:truthy
  push:
    paths:
      - src/**/*.ts
      - tests/**/*.ts
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Install npm dependencies
        run: |
          npm install --save-dev eslint \
              @eslint/js \
              @types/eslint__js \
              @types/node \
              @types/jest \
              @typescript-eslint/eslint-plugin \
              @typescript-eslint/parser \
              eslint-config-prettier \
              eslint-plugin-jest \
              eslint-plugin-prettier \
              globals \
              jest \
              prettier \
              ts-jest \
              ts-node \
              typescript \
              typescript-eslint

      - name: Run npm run test
        run: npm run test
